from .base import ConvolutionLayerBase, ConvolutionLayer2DBase, ConvolutionLayer3DBase
from .chisel import ConvolutionLayerChisel
from .hls import ConvolutionLayerHLS, ConvolutionLayer3DHLS
from .sparse import ConvolutionLayerSparseChisel, ConvolutionLayerSparsePointwiseChisel, ConvolutionLayerSparseSkippingChisel
