[device]
name = "u250"
part = "xcu250-figd2104-2L-e"
board = "xilinx.com:au250:part0:1.3"

[resources]
DSP   = 12288
BRAM  = 5376
FF    = 3456000
LUT   = 1728000
URAM  = 1280

[system]
board_frequency = 250 # in MHz
memory_bandwidth = 614.4 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512

[ethernet]
bandwidth = 100.0 # in Gbps
latency = 0.000005 # in seconds