[device]
name = "u250"
part = "xcu250-figd2104-2L-e"
board = "xilinx.com:zc702:part0:1.4"

[resources]
DSP   = 11508
BRAM  = 4000
FF    = 2760000
LUT   = 1380000
URAM  = 1280

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 100.0 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512

