[device]
name = "vc709"
#family = ""
part = "xc7vx690tffg1761-2"
board = "" #TODO: add board file

[resources]
DSP   = 3600
BRAM  = 2940
FF    = 866000
LUT   = 433000

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 204.8 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 128