[device]
name = "vus440"
#family = ""
part = "" # TODO
board = "" #TODO: add board file

[resources]
DSP   = 2880
BRAM  = 5040
FF    = 5065000
LUT   = 2532000

[system]
board_frequency = 300 # in MHz
memory_bandwidth = 135.83 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512
