[device]
name = "zcu104"
# part = "xczu7ev-ffvb1156-2-e"
part = "xczu7ev-ffvc1156-2-e"
board = "" #TODO: add board file

[resources]
DSP   = 1728
BRAM  = 624
FF    = 504000
LUT   = 461000

[system]
board_frequency = 160 # in MHz
memory_bandwidth = 135.83 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512
