[device]
name = "zcu104"
part = "xczu7ev-ffvc1156-2-e"
board = "" #TODO: add board file

[resources]
DSP   = 1728
BRAM  = 624
FF    = 460800
LUT   = 230400
URAM  = 96

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 153.6 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512
