[device]
name = "zu3eg"
part = "" # TODO
board = "" # TODO

[resources]
DSP   = 360
BRAM  = 432
FF    = 141120
LUT   = 70560
URAM  = 0

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 100.0 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512

