[device]
name = "zu7ev"
#family = ""
part = "xc7z020clg484-1"
board = "xilinx.com:zc702:part0:1.4"

[resources]
DSP   = 1728
BRAM  = 624
FF    = 460800
LUT   = 230400

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 100.0 # in Gbps
reconfiguration_time = 0.08255 # in seconds
axi_ports = 2
axi_data_width = 128
